spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: ${ZIPKIN_URI}
  cloud:
    loadbalancer:
      ribbon:
        enabled: true
    stream:
      bindings:
        output:
          destination: clientChangeTopic
          content-type: application/json
      kafka:
        binder:
          zkNodes: zookeeper
          brokers: kafkaserver

#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI}
server:
  port: 8081

security:
  oauth2:
    authorization:
      check-token-access: isAuthenticated()
    resource:
      user-info-uri: ${AUTH_URI}