eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  #  ignored-services: '*'
  routes:
    customer: /cust/**
    stockquote: /stockquote/**
  ribbon:
    eager-load:
      enabled: true
  sensitive-headers: Cookie,Set-Cookie
server:
  port: 5555
#
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8901/user

signing:
  key: 345345fsdgsf5345

spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411