version: "3.9"
services:
  zuulserver:
    container_name: zuulserver
    image: ngomalalibo/zuulserver
    mem_limit: 1024m
    mem_reservation: 128M
    ports:
      - "5555:5555"
    environment:
      MONGODB_DATABASE_STOCKS_ATLAS: "mongodb+srv://stocks:stocks@mflix-lfo1z.mongodb.net/test?retryWrites=true&w=majority"
      ENCRYPT_KEY: "IMSYMMETRIC"
      EUREKA_URI: "http://3.120.244.222:8761/eureka/"
      AUTH_URI: "http://18.156.2.42:8901/user"
      CONF_URI: "http://18.156.2.42:8888"
      DATABASE_URI: "mongodb+srv://stocks:stocks@mflix-lfo1z.mongodb.net/test?retryWrites=true&w=majority"
      ZIPKIN_URI: "http://3.120.244.222:9411"
      ZUUL_URI: "http://18.156.118.141:5555"
      BOOTSTRAP_SERVERS_CONFIG: "18.195.186.89:9092"