eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level: warn
server:
  port: 8901

security:
  oauth2:
    authorization:
      check-token-access: isAuthenticated()
    client:
      client-id: stocktrading
      client-secret: thisissecret
    resource:
      user-info-uri: http://localhost:8901/user

signing:
  key: 345345fsdgsf5345