spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: true
    stream:
      bindings:
        input:
          destination: clientChangeTopic
          content-type: application/json
          group: stockGroup
      kafka:
        binder:
          zkNodes: zookeeper
          brokers: kafkaserver
  zipkin:
    base-url: ${ZIPKIN_URI}
  sleuth:
    sampler:
      probability: 1.0

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI}

server:
  port: 8085

security:
  oauth2:
    authorization:
      check-token-access: isAuthenticated()
    client:
      client-id: stocktrading
      client-secret: thisissecret
    resource:
      user-info-uri: ${AUTH_URI}

signing:
  key: 345345fsdgsf5345