eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8901/user
    client:
      client-id: stockquote
      client-secret: thisissecret
      grant-type: password