server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        native:
          searchLocations: file:\Users\Ngo\Documents\IntelliJProjects\microservices\confsvr\src\main\resources\config

encrypt:
  key: IMSYMMETRIC

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG